Use https with pypi.python.org.
Fixes exception:

    Exception occurred:
      File "../.pyenv/versions/3.5.1/lib/python3.5/xmlrpc/client.py", line 1166, in single_request
         dict(resp.getheaders())
    xmlrpc.client.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>